name: myapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  flutter_bloc: ^9.0.0
  http: ^1.0.0
  http_parser: ^4.0.0
  equatable: ^2.0.3
  google_fonts: ^6.2.1
  go_router: ^10.1.2
  camera: ^0.10.5

  # firebase DB
  get_storage: ^2.1.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4

  # messaging
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.1

  # other
  connectivity_plus: ^5.0.1
  pin_code_fields: ^8.0.0
  iconsax: ^0.0.8
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/