// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-6ir2Jd456e8SqNICTNzZHQhw__ajzIo',
    appId: '1:772642062450:web:c5bf0865cd3314742682eb',
    messagingSenderId: '772642062450',
    projectId: 'easyfit-8c226',
    authDomain: 'easyfit-8c226.firebaseapp.com',
    storageBucket: 'easyfit-8c226.firebasestorage.app',
    measurementId: 'G-J6WGQGX17G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIj5ZPFrdCrLU17B6pubFtLpMqT7c6Zus',
    appId: '1:772642062450:android:c6392a4ef87a1b5a2682eb',
    messagingSenderId: '772642062450',
    projectId: 'easyfit-8c226',
    storageBucket: 'easyfit-8c226.firebasestorage.app',
  );

}